baseURL = 'https://derfuning.github.io/'
languageCode = 'zh-cn'
title = 'DerFuning 的技术博客'
theme = 'PaperMod'

[params]
env = "production"
author = "DerFuning"
defaultTheme = "auto"

[params.homeInfoParams]
Title = "欢迎来到我的技术博客"
Content = "分享技术心得、踩坑经验和学习笔记"

[[menu.main]]
name = "文章"
url = "/posts/"
weight = 1

[[menu.main]]
name = "标签"
url = "/tags/"
weight = 2
